### ISSUE TITLE
Securing account with two-factor authentication (2FA)

### ISSUE THREAD

**Issue by ishkurko** [xm-online/xm-online#1]
## About Two-Factor Authentication

Two-factor authentication, or 2FA, is a way of logging into websites that require more than just a password. Using a password to log into a website is susceptible to security threats because it represents a single piece of information a malicious person needs to acquire. The added security that 2FA provides is requiring additional information to sign in.

## 2FA configuration for UAA

There should be a present mechanism to extend second authentication factor with different strategies. Initial implementation could be with following mechanisms:

### Configuring two-factor authentication via a TOTP over Telegram

A Time-based One-Time Password (TOTP) automatically generates an authentication code that changes after a certain period of time and sends it to the Telegram account (user's Telegram account should be entered in personal setting). 

###  Configuring two-factor authentication via secret codes

After successfully setting up this type of two-factor authentication, the user should get a list with secret codes on the e-mail and then use them in authentication.

## 2FA on the login page

The input field for second authentication factor should be shown after password check or login via social network if the user has 2FA feature in enable state.

## Disabling/Enable 2FA for personal account

The user should be able to disable/enable 2FA for the personal account on the settings page. He/she could choose second authentication factor base on the UAA configuration.

**Comment by major13ua** [comment]
Please add Configuring two-factor authentication via a TOTP over Email

**Comment by major13ua** [comment]
@ishkurko 2FA with email channel added
1. 2FA on/off on tenant level
2. 2FA on/off in admin section for account
3. 2FA on/of in user settings

**Comment by adovbnya** [comment]
To enable 2FA first enable it on tenant level. Then each user of this tenant can enable/disable 2FA individually.

Current implementation use e-mail channel to send 2FA OTP, but can be extended (by implementing interfaces) to use any other channels like SMS, Viber, Telegram, etc. 

**Tenant level 2FA** can be enabled in tenant config file: `security.tfaEnabled: true`.
2FA configuration example for XM tenant in GIT xm-ms-conifg-repository:
`/config/tenants/XM/uaa/uaa.yml`
```
---
security:
    tfaEnabled: true
    tfaDefaultOtpChannelType: email
    tfaEnabledOtpChannelTypes:
      - email
    tfaAccessTokenValiditySeconds: 30
```

**User level 2FA** enabling has 2 steps:
1. Getting 2FA OTP channel specifications available for user:
```
curl -X GET \
  https://<tenant-domain>/uaa/api/account/tfa_available_otp_channel_specs \
  -H 'authorization: bearer <access-token-value>' \
  -H 'cache-control: no-cache'
```
Response body:
```
{
    "email": [
        {
            "channelType": "email",
            "destination": "xm@xm-online.com" 
        }
    ]
}
```
2. Enable 2FA for current logged in user (with OTP channel specification):
```
curl -X POST \
  https://<tenant-domain>/uaa/api/account/tfa_enable \
  -H 'authorization: bearer <access-token-value>' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
    "otpChannelSpec": {
        "channelType": "email",
        "destination": "xm@xm-online.com" 
    }
}'
```
On success HTTP 200 (OK) is returned.

**Comment by adovbnya** [comment]
2FA XM flow:
![xmo-2fa-flow-v1 0](https://user-images.githubusercontent.com/6270835/36368334-6891d40a-155f-11e8-8048-fc7c6492aa05.png)
