### ISSUE TITLE
Application menu: Icons for Entities

### ISSUE THREAD

**Issue by evantonov** [xm-online/xm-online#10]
Add an option «show/no show» icons of entities in the left Application menu. If option «no show» then a left padding should be (nested list). First letters aren't usable to find a necessary entity.

**Comment by ishkurko** [comment]
You could use parameter `iconsInMenu: true` the UI specification. Result will be as follow:
<img width="244" alt="screen shot 2018-03-05 at 12 07 32 pm" src="https://user-images.githubusercontent.com/7899393/36969370-f443f74e-206d-11e8-89aa-db5b332749ad.png">
