### ISSUE TITLE
Correct style on the bootstrap form control: select 

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-online#102]
Now the select list looks like:

![2018-05-23 15 05 27](https://user-images.githubusercontent.com/25796355/40423367-fe505ae6-5e9a-11e8-9e07-9d4d20ea7060.png)
 
Please, correct element style in line
Also, if you choose an element you don't see anything in list

![2018-05-23 14 58 58](https://user-images.githubusercontent.com/25796355/40423486-651bae38-5e9b-11e8-94ec-0118f2de2dc5.png)

**Comment by ishkurko** [comment]
There was a problem with newer version of a third-party library. Fixed.
