### ISSUE TITLE
Can't deploy xm-online using docker compose method

### ISSUE THREAD

**Issue by alextsm** [xm-online/xm-online#103]
Hello, I'm trying to deploy xm-online using docker compose method.
But, as I can see, these components are always in restarting state: 
xm2local_entity-app
xm2local_gate-app
xm2local_uaa-app
xm2local_dashboard-app
xm2local_balance-app
xm2local_timeline-app

I have registered only one service in consul "xm-tenant-config-hazelcast-cluster", looks like something wrong with it>. But, each component can reach each other using docker network 

Here are a part of logs from each component:

**xm2local_entity-app**

cal_entity-app.1.zye6gowk73iq@xmonline    | 2018-06-20 20:02:08,724 WARN  [main] [5onZbutQ] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
xm2local_entity-app.1.zw4aqfq7dtwg@xmonline    | 2018-06-20 14:15:55,266 WARN  [main] [tFBGWAro] AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'databaseConfiguration' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/entity/config/DatabaseConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.web.client.HttpClientErrorException: 400 Bad Request

**xm2local_gate-app**

xm2local_gate-app.1.zzhm8plmvr5o@xmonline    | 2018-06-20 09:00:06,188 WARN  [main] [9K1eTAP8] URLConfigurationSource: No URLs will be polled as dynamic configuration sources
xm2local_gate-app.1.zws3funwk7el@xmonline    | 2018-06-20 12:12:21,205 ERROR [main] [5gK36skQ] RestCallLoggingAspect: rest:stop  RestTemplate:exchange --> request = url=http://config/api/private/config_map?version,method=GET,requestEntity=<{Content-Type=[text/plain;charset=UTF-8]}>,responseType=ParameterizedTypeReference<java.util.Map<java.lang.String, com.icthh.xm.commons.config.domain.Configuration>>,uriVariables=[Ljava.lang.Object;@285f38f6, error = org.springframework.web.client.HttpClientErrorException: 400 Bad Request org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:63) ... com.icthh.xm.commons.config.client.config.XmRestTemplateConfiguration$1.handleError(XmRestTemplateConfiguration.java:39)..., time = 345 ms

**xm2local_uaa-app**

xm2local_uaa-app.1.zigxjlvf1ujd@xmonline    | 2018-06-21 15:41:16,422 WARN  [main] [FlDh4mKs::XM] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
uaa-app.1.zjcu8nn4iunc@xmonline    | 2018-06-21 14:02:42,293 INFO  [main] [1AifodEc::XM] DynamicServerListLoadBalancer: DynamicServerListLoadBalancer for client config initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=config,current list of Servers=[10.0.0.3:8084],Load balancer stats=Zone stats: {unknown=[Zone:unknown;	Instance count:1;	Active connections count: 0;	Circuit breaker tripped count: 0;	Active connections per server: 0.0;]
uaa-app.1.zujkmi7lmle6@xmonline    | },Server stats: [[Server:10.0.0.3:8084;	Zone:UNKNOWN;	Total Requests:0;	Successive connection failure:0;	Total blackout seconds:0;	Last connection made:Thu Jan 01 03:00:00 EET 1970;	First connection made: Thu Jan 01 03:00:00 EET 1970;	Active Connections:0;	total failure count in last (1000) msecs:0;	average resp time:0.0;	90 percentile resp time:0.0;	95 percentile resp time:0.0;	min resp time:0.0;	max resp time:0.0;	stddev resp time:0.0
uaa-app.1.zjcu8nn4iunc@xmonline    | 2018-06-21 14:02:44,456 ERROR [main] [1AifodEc::XM] RestCallLoggingAspect: rest:stop  RestTemplate:exchange --> request = url=http://config/api/private/config_map?version,method=GET,requestEntity=<{Content-Type=[text/plain;charset=UTF-8]}>,responseType=ParameterizedTypeReference<java.util.Map<java.lang.String, com.icthh.xm.commons.config.domain.Configuration>>,uriVariables=[Ljava.lang.Object;@203d1d93, error = org.springframework.web.client.HttpClientErrorException: 400 Bad Request org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:63) ... com.icthh.xm.commons.config.client.config.XmRestTemplateConfiguration$1.handleError(XmRestTemplateConfiguration.java:39)..., time = 8926 ms

**xm2local_dashboard-app**

xm2local_dashboard-app.1.zxrw9gfvzxt9@xmonline    | 2018-06-21 03:19:41,133 WARN  [main] [wEvpufxU] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
xm2local_dashboard-app.1.zz8j4k7ouxlg@xmonline    | 2018-06-20 21:47:10,919 WARN  [main] [xtJ7f9KQ] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
xm2local_dashboard-app.1.zz8j4k7ouxlg@xmonline    | 2018-06-20 21:47:25,813 WARN  [main] [xtJ7f9KQ] AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'databaseConfiguration' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/dashboard/config/DatabaseConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.web.client.HttpClientErrorException: 400 Bad Request
xm2local_dashboard-app.1.zxrw9gfvzxt9@xmonline    | 2018-06-21 03:19:54,261 ERROR [main] [wEvpufxU] SpringApplication: Application startup failed
xm2local_dashboard-app.1.zz8j4k7ouxlg@xmonline    | 2018-06-20 21:47:26,183 ERROR [main] [xtJ7f9KQ] SpringApplication: Application startup faile

**xm2local_balance-app**

xm2local_balance-app.1.zz0s6u06a2ne@xmonline    | 2018-06-20 10:06:27,503 WARN  [main] [DMYjxlp0] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
gframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'databaseConfiguration' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/balance/config/DatabaseConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantListRepository' defined in class path resource [com/icthh/xm/commons/config/client/config/XmConfigTenantConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.web.client.HttpClientErrorException: 400 Bad Request

**xm2local_timeline-app**

xm2local_timeline-app.1.zyexez2s2qi2@xmonline    | 2018-06-20 21:48:48,787 WARN  [main] [TFFgVHhs] URLConfigurationSource: No URLs will be polled as dynamic configuration sources.
xm2local_timeline-app.1.zyexez2s2qi2@xmonline    | 2018-06-20 21:48:54,413 WARN  [main] [TFFgVHhs] AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationStartup' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/timeline/listeners/ApplicationStartup.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timelineEventConsumer' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/timeline/repository/kafka/TimelineEventConsumer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timelineService' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/timeline/service/TimelineService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timelineRepository' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/timeline/repository/cassandra/TimelineRepository.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tenantPropertiesService' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/icthh/xm/ms/timeline/service/TenantPropertiesService.class]: Initialization of bean failed; nested exception is org.springframework.web.client.HttpClientErrorException: 400 Bad Request

**Comment by somelchuk** [comment]
Hello, we updated docker compose file, and changed version xm-config-app in the docker-compose.yml. 
Pls  make git pull and running deploy xm-online.

**Comment by alextsm** [comment]
Everything works fine now!
Thanks a lot!
One more question if you don't mind
Could you please explain where can we  find the default login/pass of xm-webapp?

**Comment by ishkurko** [comment]
By default `<tenant-name>/P@ssw0rd`. So, in your case, please try `xm/P@ssw0rd`

**Comment by alextsm** [comment]
It's working! Thanks!
