### ISSUE TITLE
The map in the AREA widget is not displayed

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#105]
The map in the [AREA widget](https://github.com/xm-online/xm-online/wiki/How-to-specify-functions#area-function) is not displayed in the tenant http://demo.xm-online.com/application/DEMO.MAMMAL/

No possibility to set the area on the map

**Comment by andrewkikot** [comment]
Hi!
The problem was that the map widget tried to init in to a div which wasn't on the page at the moment.
Fixed and updated.
