### ISSUE TITLE
Elements of the interface create a duplicate while saving

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#106]
When you change user settings and save changes, interface elements create a duplicate when you save, but changes are recorded
![1](https://user-images.githubusercontent.com/34374238/41914372-8aaf7e9c-795b-11e8-8593-9f10c9453b88.png)
![2](https://user-images.githubusercontent.com/34374238/41914382-975768f8-795b-11e8-87c1-9039319e7215.png)
![3](https://user-images.githubusercontent.com/34374238/41914387-99f3025c-795b-11e8-9e08-54252c3e4f0f.png)

**Comment by andrewkikot** [comment]
Indeed, the problem existed.
It now has been fixed in development branch.

**Comment by akobiak** [comment]
CHECKED
VERIFIED
