### ISSUE TITLE
Improvements in localization

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#110]
1) If in the list one item "CURRENT LOCATION" and do not choose it - then it does not allow to save the form (ERROR)
Suggestion: If the item is not selected (or "LOCATION CURRENT" is selected) - then set the location to the coordinates of the browser. If another item is selected, then it is possible to assign a location to the user's choice.
![image](https://user-images.githubusercontent.com/34374238/42214262-b4f7c854-7ec3-11e8-8171-3ce9a1f83ca5.png)

2) If "COUNTRY" is not selected, an extra key is displayed
Suggestions: Do not print keys of non-filled values
![image](https://user-images.githubusercontent.com/34374238/42214717-f65732d4-7ec4-11e8-8a0b-0a7b6a6385ea.png)

3) Usually the latitude and longitude are first displayed.
Suggestion: Swap
![image](https://user-images.githubusercontent.com/34374238/42214849-4b52ec92-7ec5-11e8-80ac-c97b96a6ba32.png)

**Comment by andrewkikot** [comment]
@akobiak, 
We appreciated your suggestions and made the appropriate changes. You can check them out on the test environment.

**Comment by akobiak** [comment]
VERIFIED
