### ISSUE TITLE
Pop-ups for Widget Offering

### ISSUE THREAD

**Issue by OksanaKysil** [xm-online/xm-online#118]
**Environment:**
Widget Offering

**A task:**
Make pop-ups for Widgets Offerings to read more information about any product. 

**Now**:
We can see a bit of text below the photo which isn't enough and all Widgets are different in size what is not attractive on the web-page. 

**Goal:**
Make Widgets Offerings the same size and with option 'read more'.  When pressing left button of mouse on the  'read more' you can see unfolded window of Offering with bigger amount of information and bigger size.

**What we have:**
![image](https://user-images.githubusercontent.com/44970565/48348742-dba99700-e68a-11e8-9ec1-e144a9ccf6d6.png)

**What we need:**
![image](https://user-images.githubusercontent.com/44970565/48349977-7061c400-e68e-11e8-98f4-827f7e1e0bcd.png)

**Comment by victor-xm** [comment]
not actual
