### ISSUE TITLE
Links are added more than the specified maximum value in entities.

### ISSUE THREAD

**Issue by herasymenkonastia** [xm-online/xm-online#122]
**Precondition:**
Open any tenant where you can add links (e.g. https://callcentre.xm-online.com).

**Steps to reproduce:**

1. Go to the Application - Operators.
2. Choose or create an entity and enter to it.
3. Add more than one links.
4. Pay attention to the result.

**Actual result:** Links have been added more than specified value in parameter “max”.

**Expected result:** You can’t add links more than specified value in parameter “max”.

![callcentre](https://user-images.githubusercontent.com/44088845/48913313-b08c2800-ee80-11e8-9842-1f6ec8971012.png)
![callcentre2](https://user-images.githubusercontent.com/44088845/48913315-b08c2800-ee80-11e8-967e-ab69eb8a77e5.png)

**Comment by ishkurko** [comment]
Duplicate:
https://github.com/xm-online/xm-online/issues/3
