### ISSUE TITLE
Incorrect version of the ElasticSearch in the default docker-compose file

### ISSUE THREAD

**Issue by ishkurko** [xm-online/xm-online#124]
**Steps to reproduce:**
Install XM^online locally via [instruction](https://github.com/xm-online/xm-online#installation-steps)

**Actual result:** The Entity Microservice could not start as the old version of the ElasticSearch specified in the docker compose [file](https://github.com/xm-online/xm-online/blob/master/assets/docker-compose.yml). 

**Expected result:** The Entity Microservice should start successfully.

**Comment by Gorynych** [comment]
#128 Pull request is created
