### ISSUE TITLE
enable functions visibility depends on the state of the entity

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#16]
Show function only in allowed set of states.

**Comment by sergeysenja1992** [comment]
We can check state inside function code. It's business logic and must be in function code.

**Comment by ishkurko** [comment]
New parameter added for the function specification.
Look at the documentation:
https://github.com/xm-online/xm-online/wiki/How-to-specify-domain-objects#functions

**Comment by victor-xm** [comment]
works on the prod
