### ISSUE TITLE
parameters during lifecycle change

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#17]
enable parameters entering in lifecycle state change actions
like: specifying reason during suspension

**Comment by ishkurko** [comment]
You could specify functions, that will change lifecycle and they have input context as input.
Configuration:
https://github.com/xm-online/xm-online/wiki/How-to-specify-domain-objects#functions
View example:
<img width="1152" alt="screen shot 2018-02-20 at 6 35 12 pm" src="https://user-images.githubusercontent.com/7899393/36436583-5a990436-166d-11e8-93c1-ea20938768f1.png">

**Comment by victor-xm** [comment]
Duplicate of #70
