### ISSUE TITLE
entity location bug

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#19]
On the screen of entity view
For location:
long: 30.51411
lat: 50.4372
location doesn't pops up
http://compass.test.xm-online.com.ua/application/ACCOUNT.CUSTOMER/1060

**Comment by ishkurko** [comment]
I could see the location (Image attached). How could we reproduce the issue?
<img width="1149" alt="screen shot 2018-01-23 at 6 45 20 pm" src="https://user-images.githubusercontent.com/7899393/35288564-b2a91550-006d-11e8-97f8-f68d7fbe0936.png">

**Comment by victor-xm** [comment]
unreproducible
