### ISSUE TITLE
Delete cascade logic for the XM Entity

### ISSUE THREAD

**Issue by ishkurko** [xm-online/xm-online#2]
## Delete behavior for the XM Entity

Method deleteXmEntity (`DELETE` `/entity/api/xm-entities/{idOrKey}`) should delete Entity with all related elements from DB and Search Server:

- tags
- attachments
- locations
- ratings
- calendars
- comments
- links with behavior for the XM Entity Links 

## Delete behavior for the XM Entity Links

XM Entity Links should be deleted based on the link `builderType`:

- `NEW` - then all links and related entities should be deleted
- `SEARCH` - then only all links should be deleted

**Comment by sergeysenja1992** [comment]
I think the strategy of deleting links should be in a separate field

**Comment by ishkurko** [comment]
> I think the strategy of deleting links should be in a separate field.
This is a dangerous possibility due to the complexity of access rights configuring.

**Comment by ishkurko** [comment]
Implemented.
