### ISSUE TITLE
add link builder type

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#20]
In the entity specification, add buildeType which combines SEARCH and NEW: allows to search and add new sub-entity.

**Comment by ishkurko** [comment]
@victor-xm Have you real cases for this feature? If SEARCH, then why it's not possible to go and exactly create new entity, when need?

**Comment by victor-xm** [comment]
Please do not close. 
Case: add a contact persons to the project: some of them are common for projects, some of them not. Logic of enterance is search, if not found add. Switch to the other interface to add in a separate interface and then search is inconvenient.

**Comment by ishkurko** [comment]
New build type added: `NEW-OR-SEARCH`.
<img width="620" alt="screen shot 2018-03-05 at 2 47 03 am" src="https://user-images.githubusercontent.com/7899393/36953522-246c9e48-2024-11e8-995a-8b51d34781ee.png">

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
