### ISSUE TITLE
Smart Description

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#22]
Use the field Description as a summary of the entity values.
Description field to be updated every time after entity values update (including properties, locations and links (not their values?). 
The format of the summary to be defined using query or regular expression.

**Comment by andrewkikot** [comment]
Hi!
At the moment we've implemented this feature.
The fields witch will be autofilled could be configured in entity spec.
You could check that out at http://xm.test.xm-online.com.ua
