### ISSUE TITLE
Cannot refresh screen after session timeout

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#23]
staying on the page:
http://compass.xm-online.com/application/PRODUCT(popup:application/PRODUCT/entity-new)
after  session timeout and refresh screen output corrupted:
![image](https://user-images.githubusercontent.com/32478250/33823865-36b80e62-de65-11e7-95db-62c027466884.png)

**Comment by ishkurko** [comment]
Fixed.

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.

**Comment by victor-xm** [comment]
![image](https://user-images.githubusercontent.com/32478250/35574018-5f1f05ec-05e1-11e8-8399-0b5477240f60.png)
Только что попробовал, получил такой вот эффект.
