### ISSUE TITLE
entity properties enum field readonly 

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#25]
In the entity properties, enum field set as read-only stays as editable.

**Comment by victor-xm** [comment]
http://ecl.xm-online.com/application/LOTS.CARTIMED/1002
field Площадка продажу

**Comment by ishkurko** [comment]
List element hasn't read-only attribute for the visualization. But you could use `disabled` in `dataFrom` configuration.
Example for form playground:
```json
{
    "schema": {
        "type": "object",
        "properties": {
            "sellingBranch": { "type": "string", "enum" : ["IAAI", "Manheim", "Copart"] }
        }
    },
    "layout": [
        { "key": "sellingBranch", "title": "Selling Branch", "disabled": true }
    ]
}
```
Note: `layout` is equivalent `dataFrom` in config.

**Comment by victor-xm** [comment]
@akobiak can you please test it?

**Comment by akobiak** [comment]
Using this example, you can not edit the value.
CONFIRMED.
