### ISSUE TITLE
[Bug] Add the functionality of editing the role and adding a role from several words

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#26]
1. Add the ability to edit the role.
2. Add the input format for the role name with a space

**Comment by ishkurko** [comment]
@akobiak 
1. It is not correct to change role name as it is could be used in external systems and this change could have unpredictable events.
2. The role is a technical concept and could be used from third parties in programmatically way. Alos, the provided format is a well-known way.

Could you provide business benefits for this request?

**Comment by akobiak** [comment]
1. I agree.
2. I agree.
Business advantages are not here. There is protection against erroneous values and the improvement of a friendly approach to managing the interface.

**Comment by victor-xm** [comment]
I believe that role requires localized display name and description.
