### ISSUE TITLE
[Tuning] Add the ability to configure the value of the ALL query for "fastSearch"

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#27]
Add the ability to configure the ALL query in the search configuration for "fastSearch"

**Comment by victor-xm** [comment]
Purpose: To eliminate showing entities in terminated state by default. 

Solution A: set a flag to disable add of All query by default for the entity.
Solution B: put an All query at the end of all other queries. Open The first configured query by default.

**Comment by ishkurko** [comment]
@akobiak
You should not specify a name, to define a query for the 'All'.
Documentation:
https://github.com/xm-online/xm-online/wiki/How-to-specify-domain-objects#fast-search

**Comment by akobiak** [comment]
Victor's proposals are relevant.
In practice, such cases are encountered.

**Comment by victor-xm** [comment]
Making the query as described in the doc: 

      fastSearch:
          - query: typeKey:USP* AND NOT stateKey:INACTIVE
          - query: typeKey:USP* AND stateKey:INACTIVE
            name: { en: "Inactive"}

produces the following result in GUI:
![screen shot 2018-03-28 at 13 08 38](https://user-images.githubusercontent.com/32478250/38022828-4386ca16-3289-11e8-9d2f-2825ce4403df.png)

**Comment by ishkurko** [comment]
Not reproducible. @victor-xm Could you try in incognito mode?
