### ISSUE TITLE
Registration flow issue

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#28]
Scenario: 
1. Go to sign up
2. Enter credentials
3. You're getting the confirmation message for account registration. Screen statys on the same page, and in few minutes form still filled and you can occasionally submit the form again. 

Solution: clear the form & switch to the Sig-in

**Comment by major13ua** [comment]
Planning to fix this week

**Comment by major13ua** [comment]
Register page
![image](https://user-images.githubusercontent.com/7502094/36269843-ee3f6598-1282-11e8-9e55-181491925976.png)

Success register transition and message
![image](https://user-images.githubusercontent.com/7502094/36269878-06c05b7c-1283-11e8-8246-82d33a241c04.png)
