### ISSUE TITLE
Add validation of the name field for entities, locations

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#29]
It's possible to create entity or location name with improper characters like "(", etc. 
There should be field validation added to allow only proper characters (TBD by dev team who knows what is permitted).

**Comment by ishkurko** [comment]
@victor-xm But where is a problem. I could create an 
<img width="469" alt="screen shot 2018-04-05 at 19 02 55" src="https://user-images.githubusercontent.com/7899393/38377715-5f69cafe-3904-11e8-9c61-8f586f43c5e0.png">
entity with different characters and then manage it.

**Comment by victor-xm** [comment]
now seems  it processes it properly ))
