### ISSUE TITLE
add tenant name validation  

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#30]
on https://xm.xm-online.com 
During the new tenant creation, it's possible to add any characters, but the tenant creation will work properly only for lowercase chars+digits (TB verified by dev team)
Add validation to the tenant creation or update with the proper error message.

**Comment by victor-xm** [comment]
to be extended to: add validation tags support in flexforms

**Comment by andrewkikot** [comment]
Hi!
We've implemented feature to config entity name validation through pattern, that can be specified in entity spec config.
You can check it out on http://xm.test.xm-online.com.ua/
For example there is a name validation pattern configured for CAR entity.
