### ISSUE TITLE
system error during entity creation / Description validation

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#35]
During entity creation, when putting too much text into the Description field system produces System Error, instead of validation during entering the data.

**Comment by ishkurko** [comment]
It could be reproduced.

**Comment by akobiak** [comment]
It could not be reproduced too.
![description](https://user-images.githubusercontent.com/34374238/35570998-8a5cfdb6-05d9-11e8-97f3-fd7f7de71223.jpg)
