### ISSUE TITLE
Edit entity issue

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#37]
Steps: 
http://b2bsales.xm-online.com/application/HSTR/964(popup:application/HSTR.NOTE/964/edit)
1. login, go to the entity: History / MoM: req (or any other)
2. press edit button
Result: form corrupted
![image](https://user-images.githubusercontent.com/32478250/34199986-29da4736-e578-11e7-9b49-b4fbccb69279.png)

**Comment by victor-xm** [comment]
Update: defect appears when during entity creation multiline  Description was added.

**Comment by ishkurko** [comment]
Fixed.
