### ISSUE TITLE
Entyt/dataForm/textarea height

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#39]
No methods from flexforms allows setting the height of textarea: neither "height", nor "rows".
Add support of textarea height definition attributes.

Main purpose: put a long text in the entity, in the ideal case with markup.

**Comment by ishkurko** [comment]
We had implemented logic with auto height for textarea element.
<img width="663" alt="textarea-with-autoheight" src="https://user-images.githubusercontent.com/7899393/34567451-092186c2-f16b-11e7-90ec-2a3b3b6d961c.png">
