### ISSUE TITLE
Registration: Implement JS password strength checker

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#4]
1. Implement simple JS password strength checker during the user registration process
Example:
https://code.tutsplus.com/tutorials/build-a-simple-password-strength-checker--net-7565

(no configuration or minimal pws requirements on this stage)

**Comment by victor-xm** [comment]
Update: 
apply to registration form same validator as for password update

**Comment by ishkurko** [comment]
Yes. We are using internal Password strength bar.
<img width="577" alt="screen shot 2017-12-26 at 9 35 39 am" src="https://user-images.githubusercontent.com/7899393/34350615-5f478026-ea20-11e7-89ad-1ab8302dc30b.png">
