### ISSUE TITLE
[Bug] On the widget, "xm-widget-available-offerings" does not select entities only for the user

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#40]
Now:
on the widget with "selector": "xm-widget-available-offerings" when selecting only its own entities for the current user (perm for the role
XMENTITY.GET_LIST with the expression # returnObject.createdBy == '# subject.userKey') outputs all entities

It is necessary:
To display entities created only by the user, but not all.

**Comment by lkozina** [comment]
You should use privilege key `XMENTITY.SEARCH` with resource condition `#returnObject.createdBy == #subject.userKey` to display entities created by user on widgets
