### ISSUE TITLE
attachment display issue

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#49]
![image](https://user-images.githubusercontent.com/32478250/34982936-9357a72a-fab4-11e7-8514-6b9b53a47c84.png)

**Comment by ishkurko** [comment]
Fixed with word-wrap style.
<img width="189" alt="attachment-long-title-fix" src="https://user-images.githubusercontent.com/7899393/35286718-6ed3eaf2-0069-11e8-8e5b-884c649ed75e.png">

**Comment by akobiak** [comment]
Verified.
Confirmed.
