### ISSUE TITLE
Enabe/Disable self-registration

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#5]
Set a flag in the tenant configuration to enable or disable self-registration of the customers.  
In the case is registration in disabled, show the text: (default)"Please contact the owner of the tenant to access the system", text can be specified in the same tenant configuration.

**Comment by ishkurko** [comment]
New parameter added for the widget configuration - `signUpEnabled`.
https://github.com/xm-online/xm-online/wiki/How-to-manage-dashboards#widget-sign-insign-up
