### ISSUE TITLE
Attachments download

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#51]
Make possible to download attachments, can be under icon: https://material.io/icons/#ic_get_app

**Comment by ishkurko** [comment]
Download attachment button with logic implemented:
<img width="199" alt="download-attachment" src="https://user-images.githubusercontent.com/7899393/35286635-35d2ca7a-0069-11e8-93d8-28bf2bdbc4ce.png">

**Comment by akobiak** [comment]
**Condition:** 
Partly
**Description of necessary changes:**

1. You can download the existing file.
2. The downloaded file can not be downloaded.
3. Large files are not downloaded (more than 10 Mb)

**Comment by victor-xm** [comment]
My test result: 
1. upload-download scenario checked for pictures
2. After uploading *.doc file:
- the picture of file type looks improper, (proposal: to have generic "file" icon with small grey letters of the mime type at right bottom side)
- while downloading file extension changed to *.dot (document template)
- the original file name is not saved, changed to name filed. Expected that it will stay as an original.
![image](https://user-images.githubusercontent.com/32478250/35325622-fd1e7578-00fc-11e8-82b3-494ec2cac9b8.png)
![image](https://user-images.githubusercontent.com/32478250/35325630-0501d258-00fd-11e8-8d94-1c854653892f.png)
3. Unpredictable sorting of attachments: expected that last added item will be first.

Tested on: http://b2bsales.xm-online.com/application/LEAD/952 

Question: Ho to see the library of mime types and relevant icons configured? 
Expect icons for mime types: pdf, pictures,

**Comment by victor-xm** [comment]
More issues:
4. 2 MB jpg filed cannot be downloaded, no message (jpg, mp4,pptx)
5. I uploaded file with "jpg" filename extension, during download it converts to "jpeg"
6. same xls->txt
7. *.log file upload doesn't work: after file selection upload widget does not specify that file is chosen.
8. After uploading pptx file, "internal server error" starts to appear after opening: http://b2bsales.xm-online.com/application/LEAD/952

**Comment by victor-xm** [comment]
9. Additional to 5,6: extension convertion: .ai->.ps
10. Double extension like .tar.gz missed, to ".gz". Here only full file name saving will help.
11. ".torrent" & ".xls" files cannot be chosen same as 7.

**Comment by ishkurko** [comment]
* We have followed images for file types: 3gp, av, divx, eps, html, js, php, rar, txt, 7z, bak, dll, exe, ico, mov, png, svg, wav, ae, bmp, doc, flv, iso, mp3, ppt, swf, zip, ai, cdr, docx, fw, jar, mp4, pptx, sys, apk, css, dw, gif, jpeg, mpeg, ps, tar, asf, csv, dwg, gz, jpg, pdf, psd, tiff.
* Implementation logic changed - the user will download file with the initial filename.

**Comment by victor-xm** [comment]
@akobiak  Can you please re-test items 1-11?

**Comment by akobiak** [comment]
After checking all the changes:
1. Files larger than 2 mb are loaded, but not downloaded
2. For files for OpenOffice and extensions "xls", "torrent", "log" and others are not substituted with "file" icon with small gray letters

**Comment by major13ua** [comment]
@akobiak @ishkurko see list export on entity app to make same implement here

**Comment by ishkurko** [comment]
Files larger than 2 Mb could be downloaded now. Please, check it.
