### ISSUE TITLE
Attachments list style

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#52]
1. Make attachment widgets twice wider: 
![image](https://user-images.githubusercontent.com/32478250/35071970-6e92290a-fbeb-11e7-9d77-c951a8fb6c52.png)

2. Change the font size of the Name to 14px

**Comment by ishkurko** [comment]
1. In this case, attachment card will spend a lot of interface space.
2. Font size decreased.
<img width="189" alt="attachment-long-title-fix" src="https://user-images.githubusercontent.com/7899393/35286944-f3b42e44-0069-11e8-9a1f-801b874cd1ef.png">

**Comment by akobiak** [comment]
Verified.
Confirmed.
