### ISSUE TITLE
no photo entities

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#53]
For entities where there is no photo added, use grayscaled entity icon instead:
![image](https://user-images.githubusercontent.com/32478250/35072346-d88b48e0-fbec-11e7-9bb3-a79b42891bd8.png)

**Comment by ishkurko** [comment]
The new logic implemented. Example for the entities list:
<img width="1150" alt="screen shot 2018-01-30 at 1 16 39 pm" src="https://user-images.githubusercontent.com/7899393/35563606-e920dba2-05bf-11e8-9d74-56cf2095ea92.png">

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
