### ISSUE TITLE
attachments adding interface

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#54]
During attachments adding:

1. Put the file name into the Name field if it wasn't added by default

2. Enable file(s) drop into the entity screen with automated adding of attachments 
- with the Name equals to the file name 
- type equals to the default one (can be set by the attachment parameter) 

![image](https://user-images.githubusercontent.com/32478250/35072395-125f09ee-fbed-11e7-9717-2252ae246eb6.png)

**Comment by ishkurko** [comment]
1. Implemented.

**Comment by victor-xm** [comment]
2nd item comes to the separate issue
