### ISSUE TITLE
optimize widgets allocation on entity view screen

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#55]
![image](https://user-images.githubusercontent.com/32478250/35072785-c6371528-fbee-11e7-8c4b-53ecb7b97ba0.png)

**Comment by victor-xm** [comment]
Expected "History" to be placed straight under "Responsible"

**Comment by ishkurko** [comment]
There is no good support of Masonry layout for bootstrap 3, that we are using as the main approach. So, the only workaround provided based on the two columns:
![screen shot 2018-03-04 at 6 14 52 pm](https://user-images.githubusercontent.com/7899393/36953343-a3a01e44-2022-11e8-8b26-db8276a3c5ba.png)

**Comment by akobiak** [comment]
CONFIRMED.
