### ISSUE TITLE
Adding entity with subtypes issue

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#56]
1. Press "Add entity" for HISTORY. You see property field "Text" as the third parameter.
2. Change type to the "MAIL" or any other. The field "Text" disappears. 
3. Change type to the "HISTORY" back. The field "Text" will not appear again.
![image](https://user-images.githubusercontent.com/32478250/35073111-2ba21e34-fbf0-11e7-953c-e3a9ed6fde3a.png)

**Comment by ishkurko** [comment]
Fixed.

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
