### ISSUE TITLE
entity with subtypes dataSpec question

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#57]
If entity with subtype like HSTR will have dataSpec 
Will this dataSpec be inherited to HSTR.MOM?

This example present in the following tenant:
http://b2bsales.xm-online.com/application/

**Comment by ishkurko** [comment]
The simple answer is yes.
HSTR.MOM will inherit dataSpec from HSTR if not overwrite it.
Same logic you could see for the ACCOUNT entity type and hierarchy.
