### ISSUE TITLE
Gui issue: wrong layers order

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#60]
![image](https://user-images.githubusercontent.com/32478250/35332932-97dbcae4-0115-11e8-9c4e-8d396b4584d4.png)

**Comment by victor-xm** [comment]
http://b2bsales.xm-online.com/application/LEAD/952
Chrome latest / mac

**Comment by ishkurko** [comment]
Fixed.

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
