### ISSUE TITLE
Attachment file upload via drop 

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#61]
Enable file(s) drop into the entity screen with automated adding of attachments

with the Name equals to the file name
type equals to the default one (can be set by the attachment parameter)

**Comment by ishkurko** [comment]
Attachment file upload via drop implemented.
![screen shot 2018-03-11 at 11 42 04 pm](https://user-images.githubusercontent.com/7899393/37258815-ef2dce8e-2585-11e8-9e27-4bb38e6ece91.png)

**Comment by akobiak** [comment]
CONFIRMED.
