### ISSUE TITLE
statistic widget GUI issue

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#62]
Align of Statistic widget is not proper to the text. Another design solution is needed. 
![image](https://user-images.githubusercontent.com/32478250/35510212-eeccc7c0-04ff-11e8-9574-ba43e14bf86d.png)

**Comment by ishkurko** [comment]
Fixed via adding `display: flex`
<img width="985" alt="screen shot 2018-02-20 at 5 49 35 pm" src="https://user-images.githubusercontent.com/7899393/36436251-6a06d30e-166c-11e8-8ffb-2118a5a82e3a.png">
