### ISSUE TITLE
UI: Wrong color of information message

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#63]
http://zillya.xm-online.com/settings

during saving personal settings message is green instead of brown

![image](https://user-images.githubusercontent.com/32478250/36063673-a851db7c-0e88-11e8-883a-a159cb71e719.png)

**Comment by victor-xm** [comment]
If the color is used interntionally and it's not a part of standard schema,
recommendation is to set the green color for text and background white or grey.

**Comment by ishkurko** [comment]
This is a standard way for the success inline messages in the theme that we are using. So, this is not a bug and I propose to leave as it is, because we will be able to get updates to the theme in a normal way in future.

**Comment by victor-xm** [comment]
Do we have the latest version of the theme now? )
