### ISSUE TITLE
Error saving updated entity 

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#64]
http://zillya.xm-online.com/application/ACCOUNT.USER/1001(popup:application/ACCOUNT.USER/1001/edit)

![image](https://user-images.githubusercontent.com/32478250/36063732-37b77e20-0e89-11e8-8b1d-22df6691be96.png)
1. Not clear the reason of rejection (maybe quotes?)
2. Not possible to edit the fields and try to save again, it's possible only to cancel and start editing again

**Comment by victor-xm** [comment]
1. Update: Seems Cyrillic is not allowed in the name

**Comment by victor-xm** [comment]
Similar error after update of the picture:
![image](https://user-images.githubusercontent.com/32478250/36063840-b43ee6c6-0e8a-11e8-8e1c-cfc7261268c1.png)

**Comment by ishkurko** [comment]
The root of the problem was in the incorrect data schema. Is it reproducible right now?

**Comment by victor-xm** [comment]
not reproducible
