### ISSUE TITLE
properties date format localization

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#66]
for the properties of the format: 
                        "docDate": {"title": "Дата доручення", "type": "string", "format": "date"}
only MM/DD/YYY format is supported. 
Regional/language formats need to be supported as well. 
Simple workaround: set format as YYYY-MM-DD as universal

**Comment by ishkurko** [comment]
We are using native date time picker.

Chrome and Edge display a date picker using the user's local calendar format. Opera 10.6+ also displays a date picker, but shows the date in the wire format. Other browsers, such as Firefox 51.0.1 and Internet Explorer 9/10/11 display a text input field with the wire format.

You could change native format via OS settings. Example for the MacOS:
<img width="670" alt="screen shot 2018-03-12 at 14 15 08" src="https://user-images.githubusercontent.com/7899393/37283405-87d626b6-2600-11e8-9c32-bc883c052261.png">

And the result will be:
<img width="563" alt="screen shot 2018-03-12 at 14 21 21" src="https://user-images.githubusercontent.com/7899393/37283464-be4356c4-2600-11e8-900e-84901ae9b8b0.png">
