### ISSUE TITLE
functions & lifecycle representation

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#67]
Change functions screen representation to the following form:
![image](https://user-images.githubusercontent.com/32478250/36077995-f2886c50-0f79-11e8-856a-6a2012857cb8.png)
Since 
1. the user cannot differentiate LC functions and others (others also can change LC)
2. There the need to put parameters to the certain LC state change

**Comment by ishkurko** [comment]
@victor-xm 
1. New logic implement:
- all default functions will be on the same tab with lifecycle and tab switcher will not be shown
- tab switcher will be shown for custom functions like AREA, etc.
Example:
<img width="1144" alt="screen shot 2018-04-12 at 12 19 27" src="https://user-images.githubusercontent.com/7899393/38668414-908fe698-3e4c-11e8-8a47-a6f1c5feda5d.png">
<img width="1144" alt="screen shot 2018-04-12 at 12 19 06" src="https://user-images.githubusercontent.com/7899393/38668421-959482c0-3e4c-11e8-864a-3f79087889a7.png">
2. You could use functions with input parameters configuration.

**Comment by akobiak** [comment]
![image](https://user-images.githubusercontent.com/34374238/38688379-98eca6ca-3e81-11e8-8315-58f668ef0421.png)
VERIFIED
