### ISSUE TITLE
multiple dataSpec

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#69]
Enable multiple dataSpec groups for the entity for the following reasons:
1. to enhance layout, when many fields are present
2. to enable different access rights definition for each group
3. to enable changing the group display/editable status depend on LC state

**Comment by ishkurko** [comment]
1. You could use `fieldset` type to have tabs with different field set.
Configuration example for the Playground:
```
{
  "schema": {
    "type": "object",
    "properties": {
      "movie": {
        "title": "Movie",
        "type": "string"
      },
      "song": {
        "title": "Song",
        "type": "string"
      }
    }
  },
  "form": [
    {
      "type": "fieldset",
      "items": [
        {
          "type": "tabs",
          "tabs": [
            {
              "title": "Video",
              "items": [
                "movie"
              ]
            },
            {
              "title": "Audio",
              "items": [
                "song"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
It will look like:
<img width="573" alt="screen shot 2018-03-05 at 3 47 36 pm" src="https://user-images.githubusercontent.com/7899393/36978352-e88a6aea-208c-11e8-90cf-0d92276e31e1.png">

**Comment by ishkurko** [comment]
2. Different access rights for part of data could significantly increase complexity in configuration. Please, use links instead or provide details in configuration management for this case.

**Comment by victor-xm** [comment]
@akobiak Can you please check the forms from tabs with Yaroslav

**Comment by ishkurko** [comment]
The last comment is not related to the issue.
