### ISSUE TITLE
parameters of the LC change state functions

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#70]
Enable setting the dataSpec of parameters for the LC state change transitions, to be used by relevant LEP assigned to this transition.

**Comment by ishkurko** [comment]
You could specify functions, that will change lifecycle and they have input context as input.
Configuration:
https://github.com/xm-online/xm-online/wiki/How-to-specify-domain-objects#functions
View example:
<img width="1152" alt="screen shot 2018-02-20 at 6 35 12 pm" src="https://user-images.githubusercontent.com/7899393/36436583-5a990436-166d-11e8-93c1-ea20938768f1.png">

**Comment by victor-xm** [comment]
Should I skip relevant LC state changes configurations then?

**Comment by victor-xm** [comment]
@ishkurko This way will make impossible to visualize the life cycle transition matrix afterwards. Are you sure?

**Comment by ishkurko** [comment]
@victor-xm 
In any case, it is an option. You could define all lifecycle state and all transitions. Then deny this via direct changes and allow changes via function calls.
