### ISSUE TITLE
add image cropper to the avatar upload

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#71]
add image cropper to the avatar upload, something like:

http://jsbin.com/fovovu/1/edit?js,output

**Comment by ishkurko** [comment]
Change avatar dialog and cropper added.
<img width="654" alt="screen shot 2018-02-28 at 12 17 38 am" src="https://user-images.githubusercontent.com/7899393/36758368-e181d0cc-1c1c-11e8-8f54-10b5de5aa9ac.png">

**Comment by akobiak** [comment]
DONE
