### ISSUE TITLE
[BUG] Don't download applications in entity

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#72]
Files can be uploaded and immediately downloaded.
After a while (hour-day) these files can't be downloaded.

Guess: Edited the configuration of this entity (dataspec and dataform), but did not delete the keys of the attachments.

Tenant:
http://tsg.xm-online.com/application/PROJECT/1154

**Comment by ishkurko** [comment]
The root of the problem in entity edit flows. Attachments rewrote content after entity edit in any case.
I made some workaround. Could you check?

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
