### ISSUE TITLE
[BUG] It is not possible to delete a block with a value.

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#74]
The deletion element (cross) is not visible. He is present and working, but not visible.
Elements in place of red squares.
Need: 
1. Provide a deletion tool.
![image](https://user-images.githubusercontent.com/34374238/36605009-195b00f2-18c8-11e8-94d9-eaaa9473b8ec.png)
2. Add to the playground the corrected forms of examples "array"
![image](https://user-images.githubusercontent.com/34374238/36605090-53d4a210-18c8-11e8-8bb3-64b3ebb035f2.png)

**Comment by major13ua** [comment]
@ishkurko - need advice

**Comment by akobiak** [comment]
1. In new elements there is no possibility of removal
![image](https://user-images.githubusercontent.com/34374238/36659412-133148f0-1add-11e8-8428-e95722d0a916.png)
2. In the examples of the playground there are no removal elements
![image](https://user-images.githubusercontent.com/34374238/36659510-68b1afe0-1add-11e8-89c2-1d6453d8b94f.png)

**Comment by ishkurko** [comment]
@akobiak  Could you try one more time and check first and second options? They should be fixed also.

**Comment by akobiak** [comment]
DONE
