### ISSUE TITLE
[Feature] Expand Management Tools "Widget Available offerings" 

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#75]
1. Add the ability to display the header of the widget "Widget Available offerings"
![image](https://user-images.githubusercontent.com/34374238/36679899-0f9ba754-1b1d-11e8-8056-efb194ad871b.png)
2. Add the ability to change the size of the offer (height and width)

**Comment by ishkurko** [comment]
1. Widget name will be displayed in the center. If not need, you could use an empty name.
2. Please, try to add parameter `rowSize` in widget configuration with value 4 - it should displays smaller cards.

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
