### ISSUE TITLE
[BUG] Fix DATA update in form of entity

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#76]
When you transition from the PROJECT entity to the FOUNDER entity, the DATA data is not updated (the PROJECT entity data is displayed)
![image](https://user-images.githubusercontent.com/34374238/36781490-ad8e96da-1c7e-11e8-806c-6e030d4d6cea.png)

**Comment by ishkurko** [comment]
Fixed.

**Comment by akobiak** [comment]
VERIFIED.
CONFIRMED.
