### ISSUE TITLE
links title issue

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#79]
For the link LEAD-> CONTACT:
http://b2bsales.xm-online.com/application/LEAD/1205

Link title is overridden by backlink value while browsing through links and backlinks.

1. Entering into the LEAD. Contact title is: "Contacts"
2. Getting into the CONTACT linked.
3. Returning back by pressing the backlink
4. On the LEAD page, Contact section title is: "Lead Company" (equals to backLink name)
Expected result: title stays  "Contacts"

**Comment by ishkurko** [comment]
It was used name replace with the back name. Fixed.
