### ISSUE TITLE
backName does not appear

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#80]
For the link LEAD-> HSTR:
http://b2bsales.xm-online.com/application/LEAD/1205

Getting into HSTR record
No group with backLinks appearing

**Comment by ishkurko** [comment]
This case appeared when no one direct link specified. Fixed and you could check in the test environment.

**Comment by victor-xm** [comment]
Cannot understand your comment, but backLinks looks working properly on the test.
Please close after delivery to prod.

**Comment by ishkurko** [comment]
This issue's list relates to the software at all and does not relate to some env. So, I am closing this issue.
