### ISSUE TITLE
[BUG] The exit form is illuminated

### ISSUE THREAD

**Issue by akobiak** [xm-online/xm-online#82]
When you are on the dashboard and trying to log out (Sign out), part of the screen is blocked and you can not exit the system (you can not see the form of confirmation of the user's action)
![image](https://user-images.githubusercontent.com/34374238/38078821-264091b8-3346-11e8-84a5-93cc45b829e5.png)

**Comment by ishkurko** [comment]
Fixed. Please, check.

**Comment by akobiak** [comment]
Not confirmed
![image](https://user-images.githubusercontent.com/34374238/38252870-ddece4f4-375d-11e8-8b01-91021a5897f2.png)

**Comment by akobiak** [comment]
CONFIRMED
