### ISSUE TITLE
Import widgets API in the MS Dashboard

### ISSUE THREAD

**Issue by ishkurko** [xm-online/xm-online#84]
Implement `import` administration API to support dashboards and widgets mass upload based on the other tenant or for the data migration.

Features to support:
- [ ] API should support model from the GET /api/widgets response
```
Inline Model [
  Inline Model 1
]
Inline Model 1 {
  config (object, optional): Widget configuration in JSON format. Format on Java level is Map ,
  dashboard (Dashboard, optional),
  id (integer, optional),
  isPublic (boolean, optional): Public widgets could be shown for not authorized users. ,
  name (string): Widget display name. ,
  selector (string): Widget unique web component selector. Examples: xm-widget-map, xm-widget- 
 profile, xm-widget-last-viewed, etc.
}
Dashboard {
  config (object, optional): Particular dashboard configuration that is not related to the layout. Format on API level is JSON. Format on Java level is Map ,
  id (integer, optional),
  isPublic (boolean, optional): Public dashboard could be shown for not authorized users. At the same time, only public widgets should be shown. ,
  layout (object, optional): Dashboard layout configuration. Format on API level is JSON. Format on Java level is Map ,
  name (string): Dashboard display name. ,
  owner (string): Dashboard owner user key. ,
  typeKey (string): Dashboard type key.
}
```

- [ ] API should have query parameter `clear`with boolean type to remove all dashboards and widgets before import if `true`. The default value is `false`.
- [ ] API call should be allowed only for the super administrator role.
- [ ] API should create a dashboard based on the `id` uniqueness or `typeKey` uniqueness if `id` not present
- [ ] API should not use widget or dashboard `ids` for inserts.

**Comment by monastyrev** [comment]
Implementation is the same as for relation XmEntity->Link

**Comment by ishkurko** [comment]
It is possible to use getDashboard API that will find and return dashboard with widgets and then use save API with dashboard and widgets at the same time.
