### ISSUE TITLE
Default languages for tenant features

### ISSUE THREAD

**Issue by victor-xm** [xm-online/xm-online#9]
In the tenant configuration:
Set default language for the tenant.
Save the selected tenant language.

**Comment by ishkurko** [comment]
Implemented. It could be used configuration for UI specification like:
```
langs:
    - en
```

**Comment by akobiak** [comment]
Additional requirements:
Set English as the default language on the start-up widget.

**Comment by ishkurko** [comment]
We had implemented logic for unauthorized user:
1. Default browser language will try applied based on the `langs` list specified
2. If not matched from previous conditions, then the first language from `langs` list will be applied
3. If not matched from previous conditions, then `en` language will be applied.

**Comment by akobiak** [comment]
CONFIRMED.
