### ISSUE TITLE
Fix translation logic on main page

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-online#96]
When we go to the main page, we see titles on different languages. After than choose English and we see titles in this language 
![image-7](https://user-images.githubusercontent.com/25796355/39923233-7ba65cf8-552b-11e8-906d-5680c6fb7bd1.png)

**Comment by sjcrisme** [comment]
@lkozina
need add to `shared-libs.module.ts`
```
 NgJhipsterModule.forRoot({
...
  defaultI18nLang: getBrowserLang()
...
}
```
which you can find in main.component.ts
