### ISSUE TITLE
UI Space between text and button 

### ISSUE THREAD

**Issue by lkozina** [xm-online/xm-online#99]
Please, Make space between range type element and submit button on form
![2018-05-23 08 30 29](https://user-images.githubusercontent.com/25796355/40405808-bbc77bc0-5e66-11e8-8ec8-efc58fcab798.png)

**Comment by andrewkikot** [comment]
Hi!
The problem was in absolute positioning of the helper-block with the text.
Clearly, this should not be the case when we do not have restrictions on the number of text entered.
At the moment, the problem is solved changing the positioning of this block.
